language: ruby
cache: bundler
branches:
  only:
  - source
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination _site
deploy:
  provider: pages
  strategy: git
  cleanup: false
  local-dir: _site/
  target-branch: master
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source