# Site setings
name: 'MULTIDIMENSIONAL'
description: 'Development, Life Style, '
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
#logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon'
baseurl:
production_url: https://hgryoo.dev/
disqus: 'hgryoo'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 'UA-74595375-1'

# Author
author:
  name: 'Hyung-Gyu Ryoo'
  image: 'logo.png'
  greetings: '관심 있는 분야 그냥 끄적이는 곳'
  description: "DBMS, 3D GIS 공간 지능에 관심이 있는 오픈소스 개발자입니다.<br>Open-source software development interested in DBMS, 3D GIS and Geo-spatial intelligence"
  bio: 'Working at CUBRID as Research Development Engineer.'

# Contact form setings
email: hyunggyu.ryoo@gmail.com
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: '@hg_ryoo'
facebook: 'hyunggyu.ryoo'
github: 'hgryoo'
linkedin: 'hgryoo9264'

# Navigation
navigation:
  - text: About
    url: /pages/about
  - text: Project
    url: /pages/project
  - text: Contact Me
    url: /pages/contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - unicode
  - jekyll-youtube
  - jekyll-toc

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
