# Site settings
title: HGRyoo's Blog
email: hyunggyu.ryoo@gmail.com
description: > # Hyung-Gyu Ryoo's Blog. GIS Developer, Researcher, Ph.D Student.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  # Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  # Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  # About : ['About', '/about', 'fa-anchor']
  Author : ['Author', '/author', 'fa-user']
  Contact : ['Contact', '/contact', 'fa-plane']
  Project : ['Projects', '/projects', 'fa-cog']
  Publication : ['Publication', '/publication', 'fa-file-text-o']

single_footer: '<p>Hyung-Gyu Ryoo &copy; 2016-2018 Powered by Writer<a href="/">latest posts</a></p>'
footer_links:
    # About: ['About', '/about']
    Author: ['Author', '/author']
    Contact: ['Contact', '/contact']

# Build settings
markdown: kramdown

# Comment settings
disqus:
  id: hgryoo

# Scholar settings
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_publications
  bibliography: bibliography.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  query: "@*"

exclude: ["Gemfile*", "Rakefile"]

plugins_dir: ./_scripts
gems: [jekyll-sitemap, jekyll-gist, jekyll-feed, jekyll/scholar, jekyll-archives, jekyll-youtube, jekyll-toc]
